#!/bin/bash

rm sw.runEalge
for chr in {1..22}
do
 sed "s/XXXIIXXX/${chr}/g" cmdTemplate_runEagle > swSeq.runEalge.chr${chr}
 echo "./swSeq.runEalge.chr${chr}" >> sw.runEalge
done
chmod +x swSeq.runEalge.chr*


rm sw.runSelscan
for chr in {1..22}
do
 sed "s/XXXIIXXX/${chr}/g" cmdTemplate_runSelscan_gmap > swSeq.runSelscan.chr${chr}
 echo "./swSeq.runSelscan.chr${chr}" >> sw.runSelscan
done
chmod +x swSeq.runSelscan.chr*
