#!/bin/bash

module load Eagle
module load selscan

## need to provide the file stem for input plink file
oriF=plinkFile

mkdir -p /lscratch/$SLURM_JOBID/tmp; \
cp ${oriF}.chrXXXIIXXX.{map,ped} /lscratch/$SLURM_JOBID/tmp/

module load plink/2.0
# ped map to vcf 
plink2 --pedmap /lscratch/$SLURM_JOBID/tmp/cp ${oriF}.chrXXXIIXXX --recode vcf --out /lscratch/$SLURM_JOBID/tmp/malawi_selScan.preEagle.chrXXXIIXXX

#cp /lscratch/$SLURM_JOBID/tmp/malawi_selScan.preEagle.chrXXXIIXXX.vcf ./tmp/

Eagle_v2.4.1 \
 --vcf=/lscratch/$SLURM_JOBID/tmp/malawi_selScan.preEagle.chrXXXIIXXX.vcf \
 --geneticMapFile=$EAGLE_HOME/tables/genetic_map_hg19_withX.txt.gz \
      --outPrefix=/lscratch/$SLURM_JOBID/tmp/chrXXXIIXXXPhase \
      --numThreads=4 \
      2>&1 | tee eagle.malawi.chrXXXIIXXX.log

cp /lscratch/$SLURM_JOBID/tmp/chrXXXIIXXXPhase.vcf.gz ./tmp/

