#!/bin/bash
module load selscan

mkdir -p /lscratch/$SLURM_JOBID/tmp; \

cp ./tmp/chrXXXIIXXXPhase.vcf.gz /lscratch/$SLURM_JOBID/tmp/

# unzip file 
gzip -d /lscratch/$SLURM_JOBID/tmp/chrXXXIIXXXPhase.vcf.gz

# get map
module load plink/1.9
plink --vcf /lscratch/$SLURM_JOBID/tmp/chrXXXIIXXXPhase.vcf  --recode --out /lscratch/$SLURM_JOBID/tmp/chrXXXIIXXXPhaseStage1

# get correct format for mappin 
awk '{ print $1"\t"$2"\t"$4"\t"$4 }' /lscratch/$SLURM_JOBID/tmp/chrXXXIIXXXPhaseStage1.map > chrXXXIIXXXnew_file.map


selscan --ihs  --vcf /lscratch/$SLURM_JOBID/tmp/chrXXXIIXXXPhase.vcf --map chrXXXIIXXXnew_file.map --out ./tmp/chrXXXIIXXXPhaseSelScan &> selscanchrXXXIIXXX.log
